version: '3'
services:
    app:
        build: .
        command: node main.js
        depends_on:
            - mongo
        ports:
            - 3085:3085
        environment:
            NODE_ENV: production
            PORT: 3085
            ROOT_URL: http://localhost:3085
            MONGO_URL: mongodb://mongo:27017/focus
    mongo:
        image: mongo
        restart: always
        volumes:
            - ./mongo-volume:/data/db
        # environment:
        #   MONGO_INITDB_ROOT_USERNAME: root
        #   MONGO_INITDB_ROOT_PASSWORD: example